// Shared fetch/parse core for the device-test queue — used by both the
// on-demand status-board CLI (dtq / device-test-status) and the SessionStart
// hook (hooks/device-test-status.mjs). No chalk/commander here so the hook
// can pull it in without a TTY-formatting dependency.
//
// Parses the fixed comment format from standards/workflows.md → "Device-test
// queue" — keep both in sync if that format changes.

const { execFile } = require('child_process');
const { promisify } = require('util');

const {
  CLAIM_MARKER,
  NOTICE_MARKER,
  parseClaim,
  activeClaim,
} = require('./claim-lib');

const execFileAsync = promisify(execFile);

// Scope table — keep in sync with skills/device-test/SKILL.md.
const REPOS = [
  { key: 'alate', repo: 'Tessellate-Studio/alate' },
  { key: 'mood-layer', repo: 'Tessellate-Studio/mood-layer' },
  { key: 'badige', repo: 'Tessellate-Studio/badige' },
];

const STATUS = {
  OPEN: 'open',
  DONE: 'done',
  FAILED: 'failed',
  NEEDS_BUILD: 'needs_build',
  UNPARSEABLE: 'unparseable',
};

/**
 * The heading glyph per state — what the queue issue looks like when you
 * scroll it in a browser, which is the one view the board never gave anyone.
 * OPEN splits by WHO is needed: an agent can run it (🤖) or a person must
 * (🙋). The `**Status:**` line stays the source of truth; the glyph mirrors
 * it, and `headingDrift` below marks any comment where the two disagree so
 * the drain restamps it.
 */
const GLYPHS = {
  [STATUS.OPEN]: '🤖',
  OPEN_HUMAN: '🙋',
  [STATUS.NEEDS_BUILD]: '🔧',
  [STATUS.DONE]: '⚪',
  [STATUS.FAILED]: '🔴',
};

const ITEM_GLYPHS = Object.values(GLYPHS);

/** The glyph an item's heading SHOULD carry, given its parsed state. */
function expectedGlyph(item) {
  if (item.state === STATUS.OPEN) {
    return item.needsHuman ? GLYPHS.OPEN_HUMAN : GLYPHS[STATUS.OPEN];
  }
  return GLYPHS[item.state] || null;
}

/**
 * Split an item comment into its FIELDS and its NOTES.
 *
 * Notes (drain observations, corrections, "why this is still blocked") are
 * appended to the item they belong to, each under a `---` rule — one comment
 * per test, its whole history in reading order, instead of a separate
 * "note for the item above" comment that stops making sense the moment
 * another item is enqueued between them.
 *
 * Fields are read only from above the boundary. A note routinely quotes the
 * item it discusses ("Expect is that the notify-me button does not appear"),
 * and every field regex here is body-wide and last-match-wins — so without
 * the split a note quoting `**Status:** OPEN` silently reopened a closed item.
 *
 * The boundary is the first rule AFTER the Status line, not the first rule in
 * the body. Items enqueued before this template routinely carry a rule
 * mid-body (the `---` above a "Generated by Claude Code" footer) with Status
 * appended below it; splitting on the first rule threw their Status away and
 * turned two live alate items into "malformed" — an invisible item, the one
 * failure this parser must never have. No Status line at all means no
 * boundary: the whole body stays fields, and the unparseable path is reached
 * exactly as before.
 */
function splitNotes(body) {
  const status = body.match(/\*\*Status:\*\*/);
  if (!status) {
    return { fields: body, notes: [] };
  }
  const after = status.index;
  const rule = /^[ \t]*---[ \t]*$/gm;
  rule.lastIndex = after;
  const boundary = rule.exec(body);
  if (!boundary) {
    return { fields: body, notes: [] };
  }
  return {
    fields: body.slice(0, boundary.index),
    notes: body
      .slice(boundary.index + boundary[0].length)
      .split(/^[ \t]*---[ \t]*$/m)
      .map(n => n.trim())
      .filter(Boolean),
  };
}

async function gh(args) {
  const { stdout } = await execFileAsync('gh', args, {
    encoding: 'utf8',
    maxBuffer: 20 * 1024 * 1024,
  });
  return stdout;
}

async function checkGhReady() {
  try {
    await execFileAsync('gh', ['auth', 'status'], { encoding: 'utf8' });
    return { ok: true };
  } catch (error) {
    if (error.code === 'ENOENT') {
      return {
        ok: false,
        message:
          'gh CLI not found. Install it from https://cli.github.com/ and run `gh auth login`.',
      };
    }
    return {
      ok: false,
      message: 'gh CLI is not authenticated. Run `gh auth login` first.',
    };
  }
}

function parseComment(comment) {
  const body = comment.body || '';

  // Device claims live on the same issue but are not tests. Without this
  // they land in the UNPARSEABLE bucket and read as malformed items.
  if (CLAIM_MARKER.test(body)) {
    return null;
  }

  // Bot notices post to this issue too — the OTA-publish record written by
  // eas-update.yml is the common one. They carry a `###` heading and no
  // Status, so without this they pile into the UNPARSEABLE bucket and the
  // board nags about "malformed items" that were never items. Six of nine
  // flagged comments on alate#562 were exactly this.
  if (NOTICE_MARKER.test(body)) {
    return null;
  }

  // Fields above the first `---`, notes below it. See splitNotes: a note
  // quoting the item it discusses must never be read as the item's own
  // fields.
  const { fields, notes } = splitNotes(body);

  // A title is `### Foo`, or a `**Foo**` opening the FIRST non-empty line —
  // the bold form predates the heading convention and some enqueues still
  // use it. First line only, deliberately: a bold run anywhere in the body
  // is ordinary prose (`**Why:** …`, `**Pre-req:** …`), and matching those
  // turned explanatory drain notes into phantom malformed items.
  const firstLine = fields.split('\n').find(l => l.trim() !== '') || '';
  const headingMatch = fields.match(/^###\s*(.+)$/m);

  // A bold opener only counts as a TITLE when the body also carries the
  // shape of a test — Steps or Expect. Plenty of legitimate commentary
  // opens bold ("**Correction to the two comments above**") and quotes
  // **PR:** / **Delivery:** while discussing someone else's item; treating
  // those as malformed items is the nagging this whole pass exists to stop.
  const looksLikeTest = /\*\*Steps:\*\*|\*\*Expect/.test(fields);
  const boldTitleMatch =
    !headingMatch && looksLikeTest
      ? firstLine.match(/^\s*\*\*(.+?)\*\*/)
      : null;

  const titleMatch = headingMatch || boldTitleMatch;
  const statusMatch = fields.match(/\*\*Status:\*\*\s*(.+?)\s*$/m);

  // Neither a title nor a Status field — this is plain commentary (a drain
  // note, a discussion reply), not an attempted queue item. Ignore it.
  if (!titleMatch && !statusMatch) {
    return null;
  }

  // Has one but not the other — looks like it was meant to be an item but
  // the format drifted. Surface it rather than silently dropping it.
  if (!titleMatch || !statusMatch) {
    return {
      state: STATUS.UNPARSEABLE,
      title: fields.split('\n')[0].slice(0, 80) || '(empty comment)',
      testId: null,
      glyph: null,
      headingDrift: true,
      notes,
      commentUrl: comment.html_url,
      createdAt: comment.created_at,
    };
  }

  // Some enqueued items arrive as ONE long line (fields joined with " — "
  // instead of newline bullets). Every field capture therefore stops at the
  // next bold **Field:** marker, not just at end-of-line — otherwise a
  // single-line item's "title" or "Needs runtime" swallows the whole body
  // and the board renders a word wall.
  const NEXT_FIELD = /\s*(?:[·—–|-]+\s*)?\*\*[A-Z][^*]*:\*\*[\s\S]*$/;
  const fieldValue = match =>
    match ? match[1].replace(NEXT_FIELD, '').trim() : null;

  const statusText = statusMatch[1].replace(NEXT_FIELD, '').trim();
  let state = STATUS.UNPARSEABLE;

  // Prefix match, NOT equality. `**Status:** OPEN — routed to another agent`
  // is a perfectly ordinary thing for a session to write, and an equality
  // check turned it into UNPARSEABLE — so a still-open item vanished from the
  // board entirely rather than showing as open. Silently losing work is the
  // worst failure this parser can have; a trailing note must not cause it.
  if (/^OPEN\b/.test(statusText)) {
    state = STATUS.OPEN;
  } else if (statusText.startsWith('✅')) {
    state = STATUS.DONE;
  } else if (statusText.startsWith('❌')) {
    state = STATUS.FAILED;
  } else if (statusText.startsWith('🔧')) {
    state = STATUS.NEEDS_BUILD;
  }

  // The PR field can be a bare number, "none", or a markdown link
  // ([#601](url)) — pull the digits out rather than the raw token, since a
  // markdown link has no internal whitespace to stop a naive \S+ match on.
  const prFieldMatch = fields.match(
    /\*\*PR:\*\*\s*([^\n]+?)(?:\s*·\s*\*\*SHA|\s*$)/m
  );
  const prField = fieldValue(prFieldMatch) || '';
  const prNumMatch = /^none\b/i.test(prField) ? null : prField.match(/#(\d+)/);
  const pr = prNumMatch ? prNumMatch[1] : null;
  const deliveryMatch = fields.match(/\*\*Delivery:\*\*\s*(.+?)\s*$/m);
  const runtimeMatch = fields.match(/\*\*Needs runtime:\*\*\s*(.+?)\s*$/m);
  const stepsMatch = fields.match(
    /\*\*Steps:\*\*\s*([\s\S]+?)(?:\n- \*\*Expect|\n\n|\*\*Expect|$)/
  );

  // `<glyph> <test id> — <what the test intends to do>`. Every part is
  // optional so the hundreds of items enqueued before this template still
  // parse; what is missing shows up as headingDrift for the drain to stamp,
  // never as a dropped item.
  //
  // The id is read narrowly on purpose — 6+ digits, and an em/en dash after
  // it. GitHub comment ids are 10 digits, while a legacy heading that opens
  // with a number opens with a small one or a date ("2026-09-02 — drain
  // results"); a looser rule ate the "2026" as an id and left the title
  // reading "09-02 — drain results", which the restamp would then write back
  // as the item's intent.
  const rawTitle = fieldValue(titleMatch) || '';
  const headingParts = rawTitle.match(
    new RegExp(
      `^(?:(${ITEM_GLYPHS.join(
        '|'
      )})\\s*)?(?:(\\d{6,})\\s*[—–]\\s*)?([\\s\\S]+)$`
    )
  );
  const glyph = headingParts ? headingParts[1] || null : null;
  const testId = headingParts ? headingParts[2] || null : null;
  const title = headingParts ? headingParts[3].trim() : rawTitle;

  const item = {
    state,
    title,
    testId,
    glyph,
    pr,
    delivery: fieldValue(deliveryMatch),
    needsRuntime: fieldValue(runtimeMatch),
    needsHuman: stepsMatch
      ? /HUMAN:/.test(stepsMatch[1])
      : /HUMAN:/.test(fields),
    statusText,
    notes,
    commentUrl: comment.html_url,
    createdAt: comment.created_at,
  };

  // The heading is a mirror of the Status line and of the comment's own id.
  // Drift means one of them was edited without the other — a ⚪ heading over
  // an OPEN item reads as finished to anyone scrolling the issue. The drain
  // restamps these (SKILL.md Step 0.3); it is never a reason to hide an item.
  item.headingDrift =
    glyph === null ||
    glyph !== expectedGlyph(item) ||
    testId === null ||
    testId !== String(comment.id);

  return item;
}

async function fetchRepoQueue(repoDef) {
  const { repo } = repoDef;
  let issueNumber = null;
  let issueUrl = null;
  try {
    // `gh api`, not `gh issue list --json`. The latter fails outright on
    // gh 2.98.0 ("invalid character '{' after object key") for every field
    // combination, which took the whole board down — the tool that is
    // supposed to answer "what is pending" printed only an error. The REST
    // endpoint returns the same data and is unaffected.
    const out = await gh([
      'api',
      `repos/${repo}/issues?labels=device-test-queue&state=open`,
    ]);

    // /issues also returns pull requests; they carry a `pull_request` key.
    const issues = JSON.parse(out || '[]')
      .filter(i => !i.pull_request)
      .map(i => ({ number: i.number, url: i.html_url }));
    if (issues.length === 0) {
      return { ...repoDef, issueNumber: null, issueUrl: null, items: [] };
    }
    issueNumber = issues[0].number;
    issueUrl = issues[0].url;
  } catch (error) {
    return { ...repoDef, error: error.message || String(error) };
  }

  try {
    const out = await gh([
      'api',
      `repos/${repo}/issues/${issueNumber}/comments`,
      '--paginate',
    ]);
    const comments = JSON.parse(out || '[]');
    const items = comments.map(parseComment).filter(Boolean);
    const claims = comments.map(parseClaim).filter(Boolean);
    return {
      ...repoDef,
      issueNumber,
      issueUrl,
      items,

      // null when the device is free (never claimed, released, or stale).
      claim: activeClaim(claims),
    };
  } catch (error) {
    return {
      ...repoDef,
      issueNumber,
      issueUrl,
      error: error.message || String(error),
    };
  }
}

async function collect(repoFilter) {
  const targets = repoFilter
    ? REPOS.filter(r => r.key === repoFilter || r.repo === repoFilter)
    : REPOS;
  if (targets.length === 0) {
    throw new Error(
      `Unknown repo "${repoFilter}". Known: ${REPOS.map(r => r.key).join(', ')}`
    );
  }
  return Promise.all(targets.map(fetchRepoQueue));
}

function daysSince(iso) {
  if (!iso) {
    return null;
  }
  const ms = Date.now() - new Date(iso).getTime();
  return Math.max(0, Math.floor(ms / (1000 * 60 * 60 * 24)));
}

module.exports = {
  REPOS,
  STATUS,
  GLYPHS,
  ITEM_GLYPHS,
  expectedGlyph,
  splitNotes,

  // Re-exported so callers get the whole queue surface from one require.
  ...require('./claim-lib'),
  checkGhReady,
  parseComment,
  fetchRepoQueue,
  collect,
  daysSince,
};
